language: python
python:
- '3.5'
install:
- pip install pytest
- pip install coveralls
script:
- coverage run --source=fnmatch2 setup.py test
deploy:
  provider: pypi
  user: lawfulhacker
  password:
    secure: "wTBBJj3glrzU8Gs4FrRGaqqk3Z8+17jEq4nRtGlhZSVcULVGriJju0LQEOFHekHPizxyX1BeBeb64eWW+nJUZOomargbKOmBZ26N7WRnIrzv1z5XfWJioj1GZb/YPxtrzYSpQ32rEBQz/tjBY2ob7MadHQHsf4m5rZuPyrHoSIbP1PMSPqmOnLaR5CjS28O7qaXxKT+8+xt3H+Yu2ofqRPTl1yD2oiuzWe7gssMcVlbha48wcSfWROqzpuTmsH+1xpE8kV6+xfDwWjRXBkJ/URbPp5ZYsaK77/C2pd9UJAWyGuJa7qpJnES8ncoq4KGN7qMQxoyVtdosPN5wY9o2NQFp5Fqbn5K9yyyzaKxfK1myGq3oqC8Qklf7uDdMqYW9FGOf2SrRwP9RvgeE/DIwoAmw4NDG7CRGNTF4C9xmEFYIRRCRc+0LIyVJJvRjGVAqrdsnLM4TgcX+eMPQtVWZ9oRWOaawW++KLkycGXPESefEcLmyfxCkxFSV3c8EMrJHwc2i3XRBKaHANxNHobAB/uDMTlhPxV61ErI/hHuNut8o2yZN9oLQetRU5ktSiYy5fwZZhtH/X4haxPssT6yAPsINVGDXNiQbBfhK+eolefB9AXAJrTw9ujXAyl0Q3BXBfHiQf5oBFBdCwGst/mVj76+jox7rxgLdAJIvVBggsuY="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: LawfulHacker/fnmatch2
after_success:
- coveralls
